






#pragma warning disable 1591
#pragma warning disable 0108
#pragma warning disable 0114

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;
using System.Diagnostics.CodeAnalysis;

// ReSharper disable InconsistentNaming


namespace DEFExample.Models.Master
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

    [ExcludeFromCodeCoverage]
	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }
	}
}

namespace DEFExample.Models.Master.sitecore.templates.Data_Exchange.Providers.Wordpress.Folders
{


 	/// <summary>
	/// IWordpress_Mappings_Applied_Actions_Root Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Folders/Wordpress Mappings Applied Actions Root</para>	
	/// <para>ID: 0cf330a7-3ad6-4b70-873c-f8d15f5255b9</para>	
	/// </summary>
	[SitecoreType(TemplateId=IWordpress_Mappings_Applied_Actions_Root_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IWordpress_Mappings_Applied_Actions_Root : IGlassBase 
	{
				}

    [ExcludeFromCodeCoverage]
	public static partial class IWordpress_Mappings_Applied_Actions_Root_Constants{

			public const string TemplateIdString = "0cf330a7-3ad6-4b70-873c-f8d15f5255b9";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Wordpress Mappings Applied Actions Root";

			

	}

	
	/// <summary>
	/// Wordpress_Mappings_Applied_Actions_Root
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Folders/Wordpress Mappings Applied Actions Root</para>	
	/// <para>ID: 0cf330a7-3ad6-4b70-873c-f8d15f5255b9</para>	
	/// </summary>
    [ExcludeFromCodeCoverage]
	[SitecoreType(TemplateId=IWordpress_Mappings_Applied_Actions_Root_Constants.TemplateIdString)] //, Cachable = true
	public partial class Wordpress_Mappings_Applied_Actions_Root  : GlassBase, IWordpress_Mappings_Applied_Actions_Root 
	{
	   
			
	}
}
namespace DEFExample.Models.Master.sitecore.templates.Data_Exchange.Providers.Wordpress.Endpoints
{


 	/// <summary>
	/// IWordPress_Endpoint Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Endpoints/WordPress Endpoint</para>	
	/// <para>ID: 1e98c461-6d75-4a9b-8d27-d2816db123ac</para>	
	/// </summary>
	[SitecoreType(TemplateId=IWordPress_Endpoint_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IWordPress_Endpoint : IGlassBase 
	{
								/// <summary>
					/// The Categories URL field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 8ace527c-c6f6-4cd7-8002-14fffef2e94d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IWordPress_Endpoint_Constants.Categories_URL_FieldName)]
					string Categories_URL  {get; set;}
			
								/// <summary>
					/// The Posts URL field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: ed630fbe-fb75-4d75-9773-93be059bf545</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IWordPress_Endpoint_Constants.Posts_URL_FieldName)]
					string Posts_URL  {get; set;}
			
								/// <summary>
					/// The Tags URL field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 5821eea6-9e5c-49fc-9126-d49bd915e06d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IWordPress_Endpoint_Constants.Tags_URL_FieldName)]
					string Tags_URL  {get; set;}
			
				}

    [ExcludeFromCodeCoverage]
	public static partial class IWordPress_Endpoint_Constants{

			public const string TemplateIdString = "1e98c461-6d75-4a9b-8d27-d2816db123ac";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "WordPress Endpoint";

					
			public static readonly ID Categories_URL_FieldId = new ID("8ace527c-c6f6-4cd7-8002-14fffef2e94d");
			public const string Categories_URL_FieldName = "Categories URL";
			
					
			public static readonly ID Posts_URL_FieldId = new ID("ed630fbe-fb75-4d75-9773-93be059bf545");
			public const string Posts_URL_FieldName = "Posts URL";
			
					
			public static readonly ID Tags_URL_FieldId = new ID("5821eea6-9e5c-49fc-9126-d49bd915e06d");
			public const string Tags_URL_FieldName = "Tags URL";
			
			

	}

	
	/// <summary>
	/// WordPress_Endpoint
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Endpoints/WordPress Endpoint</para>	
	/// <para>ID: 1e98c461-6d75-4a9b-8d27-d2816db123ac</para>	
	/// </summary>
    [ExcludeFromCodeCoverage]
	[SitecoreType(TemplateId=IWordPress_Endpoint_Constants.TemplateIdString)] //, Cachable = true
	public partial class WordPress_Endpoint  : GlassBase, IWordPress_Endpoint 
	{
	   
						/// <summary>
				/// The Categories URL field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 8ace527c-c6f6-4cd7-8002-14fffef2e94d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IWordPress_Endpoint_Constants.Categories_URL_FieldName)]
				public virtual string Categories_URL  {get; set;}
					
						/// <summary>
				/// The Posts URL field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ed630fbe-fb75-4d75-9773-93be059bf545</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IWordPress_Endpoint_Constants.Posts_URL_FieldName)]
				public virtual string Posts_URL  {get; set;}
					
						/// <summary>
				/// The Tags URL field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 5821eea6-9e5c-49fc-9126-d49bd915e06d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IWordPress_Endpoint_Constants.Tags_URL_FieldName)]
				public virtual string Tags_URL  {get; set;}
					
			
	}
}
namespace DEFExample.Models.Master.sitecore.templates.Example.Content_Type.Blogs
{


 	/// <summary>
	/// IBlog Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Example/Content Type/Blogs/Blog</para>	
	/// <para>ID: 23eaf5eb-a1de-4582-867e-adbe7821ac73</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBlog_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IBlog : IGlassBase , global::DEFExample.Models.Master.sitecore.templates.Example.Interfaces.I_Blog
	{
				}

    [ExcludeFromCodeCoverage]
	public static partial class IBlog_Constants{

			public const string TemplateIdString = "23eaf5eb-a1de-4582-867e-adbe7821ac73";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Blog";

					
			public static readonly ID Author_FieldId = new ID("a088ed8c-0861-426f-a46d-bd250b3997bf");
			public const string Author_FieldName = "Author";
			
					
			public static readonly ID Categories_FieldId = new ID("71a8d0db-345a-41bc-ab09-d7b5ce4dc50a");
			public const string Categories_FieldName = "Categories";
			
					
			public static readonly ID Comment_Status_FieldId = new ID("f7e8892f-1de3-42ab-9077-6d22f8637938");
			public const string Comment_Status_FieldName = "Comment Status";
			
					
			public static readonly ID Content_FieldId = new ID("01dfd93b-ee28-4021-9486-10ceed6e2329");
			public const string Content_FieldName = "Content";
			
					
			public static readonly ID Date_Gmt_FieldId = new ID("63e76bee-5109-48e9-a6e0-9bcfb0e39d15");
			public const string Date_Gmt_FieldName = "Date Gmt";
			
					
			public static readonly ID Date_FieldId = new ID("88746c69-6b1b-4670-a2ab-3e410dc9f46d");
			public const string Date_FieldName = "Date";
			
					
			public static readonly ID Excerpt_FieldId = new ID("30a0549c-aad0-48de-98ce-4ca6679a5161");
			public const string Excerpt_FieldName = "Excerpt";
			
					
			public static readonly ID Image_Link_FieldId = new ID("ab051020-8659-48e8-bfe1-b838b5d13160");
			public const string Image_Link_FieldName = "Image Link";
			
					
			public static readonly ID Link_FieldId = new ID("ccf5a196-60e4-4108-b9e6-df87e8d34d6c");
			public const string Link_FieldName = "Link";
			
					
			public static readonly ID Modified_Date_Gmt_FieldId = new ID("04e7e313-2681-4ec3-a5f8-9d9f4cf623ac");
			public const string Modified_Date_Gmt_FieldName = "Modified Date Gmt";
			
					
			public static readonly ID Modified_Date_FieldId = new ID("e5962ad0-9ab7-4abe-a699-18c0a2a29454");
			public const string Modified_Date_FieldName = "Modified Date";
			
					
			public static readonly ID Ping_Status_FieldId = new ID("40563313-903a-471e-8cd5-1abb5897b38f");
			public const string Ping_Status_FieldName = "Ping Status";
			
					
			public static readonly ID Slug_FieldId = new ID("f80740ff-ff83-4a59-9885-c2c4c0b30c91");
			public const string Slug_FieldName = "Slug";
			
					
			public static readonly ID Status_FieldId = new ID("7f70c3a2-424d-4427-b500-17a79bcace31");
			public const string Status_FieldName = "Status";
			
					
			public static readonly ID Sticky_FieldId = new ID("1672750f-3b0d-448d-8ab4-68b101dab9d4");
			public const string Sticky_FieldName = "Sticky";
			
					
			public static readonly ID Tags_FieldId = new ID("0b512b3b-d866-466f-8f78-e017bbed3040");
			public const string Tags_FieldName = "Tags";
			
					
			public static readonly ID Title_FieldId = new ID("27481025-7bf4-4fd5-9f84-d24c54ecae19");
			public const string Title_FieldName = "Title";
			
					
			public static readonly ID Type_FieldId = new ID("94a67fdb-8647-44a9-9cf3-bc44c7b5b480");
			public const string Type_FieldName = "Type";
			
					
			public static readonly ID Wordpress_Id_FieldId = new ID("3a289128-d373-4a81-905e-f31abf44de69");
			public const string Wordpress_Id_FieldName = "Wordpress Id";
			
			

	}

	
	/// <summary>
	/// Blog
	/// <para></para>
	/// <para>Path: /sitecore/templates/Example/Content Type/Blogs/Blog</para>	
	/// <para>ID: 23eaf5eb-a1de-4582-867e-adbe7821ac73</para>	
	/// </summary>
    [ExcludeFromCodeCoverage]
	[SitecoreType(TemplateId=IBlog_Constants.TemplateIdString)] //, Cachable = true
	public partial class Blog  : GlassBase, IBlog 
	{
	   
						/// <summary>
				/// The Author field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: a088ed8c-0861-426f-a46d-bd250b3997bf</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBlog_Constants.Author_FieldName)]
				public virtual string Author  {get; set;}
					
						/// <summary>
				/// The Categories field.
				/// <para></para>
				/// <para>Field Type: Treelist</para>		
				/// <para>Field ID: 71a8d0db-345a-41bc-ab09-d7b5ce4dc50a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBlog_Constants.Categories_FieldName)]
				public virtual IEnumerable<Guid> Categories  {get; set;}
					
						/// <summary>
				/// The Comment Status field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f7e8892f-1de3-42ab-9077-6d22f8637938</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBlog_Constants.Comment_Status_FieldName)]
				public virtual string Comment_Status  {get; set;}
					
						/// <summary>
				/// The Content field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 01dfd93b-ee28-4021-9486-10ceed6e2329</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBlog_Constants.Content_FieldName)]
				public virtual string Content  {get; set;}
					
						/// <summary>
				/// The Date Gmt field.
				/// <para></para>
				/// <para>Field Type: Date</para>		
				/// <para>Field ID: 63e76bee-5109-48e9-a6e0-9bcfb0e39d15</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBlog_Constants.Date_Gmt_FieldName)]
				public virtual DateTime Date_Gmt  {get; set;}
					
						/// <summary>
				/// The Date field.
				/// <para></para>
				/// <para>Field Type: Date</para>		
				/// <para>Field ID: 88746c69-6b1b-4670-a2ab-3e410dc9f46d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBlog_Constants.Date_FieldName)]
				public virtual DateTime Date  {get; set;}
					
						/// <summary>
				/// The Excerpt field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 30a0549c-aad0-48de-98ce-4ca6679a5161</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBlog_Constants.Excerpt_FieldName)]
				public virtual string Excerpt  {get; set;}
					
						/// <summary>
				/// The Image Link field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ab051020-8659-48e8-bfe1-b838b5d13160</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBlog_Constants.Image_Link_FieldName)]
				public virtual string Image_Link  {get; set;}
					
						/// <summary>
				/// The Link field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ccf5a196-60e4-4108-b9e6-df87e8d34d6c</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBlog_Constants.Link_FieldName)]
				public virtual string Link  {get; set;}
					
						/// <summary>
				/// The Modified Date Gmt field.
				/// <para></para>
				/// <para>Field Type: Date</para>		
				/// <para>Field ID: 04e7e313-2681-4ec3-a5f8-9d9f4cf623ac</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBlog_Constants.Modified_Date_Gmt_FieldName)]
				public virtual DateTime Modified_Date_Gmt  {get; set;}
					
						/// <summary>
				/// The Modified Date field.
				/// <para></para>
				/// <para>Field Type: Date</para>		
				/// <para>Field ID: e5962ad0-9ab7-4abe-a699-18c0a2a29454</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBlog_Constants.Modified_Date_FieldName)]
				public virtual DateTime Modified_Date  {get; set;}
					
						/// <summary>
				/// The Ping Status field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 40563313-903a-471e-8cd5-1abb5897b38f</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBlog_Constants.Ping_Status_FieldName)]
				public virtual string Ping_Status  {get; set;}
					
						/// <summary>
				/// The Slug field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f80740ff-ff83-4a59-9885-c2c4c0b30c91</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBlog_Constants.Slug_FieldName)]
				public virtual string Slug  {get; set;}
					
						/// <summary>
				/// The Status field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 7f70c3a2-424d-4427-b500-17a79bcace31</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBlog_Constants.Status_FieldName)]
				public virtual string Status  {get; set;}
					
						/// <summary>
				/// The Sticky field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 1672750f-3b0d-448d-8ab4-68b101dab9d4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBlog_Constants.Sticky_FieldName)]
				public virtual string Sticky  {get; set;}
					
						/// <summary>
				/// The Tags field.
				/// <para></para>
				/// <para>Field Type: Treelist</para>		
				/// <para>Field ID: 0b512b3b-d866-466f-8f78-e017bbed3040</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBlog_Constants.Tags_FieldName)]
				public virtual IEnumerable<Guid> Tags  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 27481025-7bf4-4fd5-9f84-d24c54ecae19</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBlog_Constants.Title_FieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The Type field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 94a67fdb-8647-44a9-9cf3-bc44c7b5b480</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBlog_Constants.Type_FieldName)]
				public virtual string Type  {get; set;}
					
						/// <summary>
				/// The Wordpress Id field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 3a289128-d373-4a81-905e-f31abf44de69</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBlog_Constants.Wordpress_Id_FieldName)]
				public virtual string Wordpress_Id  {get; set;}
					
			
	}
}
namespace DEFExample.Models.Master.sitecore.templates.Example.Interfaces
{


 	/// <summary>
	/// I_Category Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Example/Interfaces/_Category</para>	
	/// <para>ID: 3b7ba518-b60c-47a2-b372-a07a353e45c5</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Category_Constants.TemplateIdString )] //, Cachable = true
	public partial interface I_Category : IGlassBase 
	{
								/// <summary>
					/// The Name field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: b111f55e-9749-440e-83b2-fac1a7404b83</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Category_Constants.Name_FieldName)]
					string Name  {get; set;}
			
								/// <summary>
					/// The Wordpress Id field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 50b0e228-46cb-4527-be90-f170f6676deb</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Category_Constants.Wordpress_Id_FieldName)]
					string Wordpress_Id  {get; set;}
			
				}

    [ExcludeFromCodeCoverage]
	public static partial class I_Category_Constants{

			public const string TemplateIdString = "3b7ba518-b60c-47a2-b372-a07a353e45c5";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Category";

					
			public static readonly ID Name_FieldId = new ID("b111f55e-9749-440e-83b2-fac1a7404b83");
			public const string Name_FieldName = "Name";
			
					
			public static readonly ID Wordpress_Id_FieldId = new ID("50b0e228-46cb-4527-be90-f170f6676deb");
			public const string Wordpress_Id_FieldName = "Wordpress Id";
			
			

	}

	
	/// <summary>
	/// _Category
	/// <para></para>
	/// <para>Path: /sitecore/templates/Example/Interfaces/_Category</para>	
	/// <para>ID: 3b7ba518-b60c-47a2-b372-a07a353e45c5</para>	
	/// </summary>
    [ExcludeFromCodeCoverage]
	[SitecoreType(TemplateId=I_Category_Constants.TemplateIdString)] //, Cachable = true
	public partial class _Category  : GlassBase, I_Category 
	{
	   
						/// <summary>
				/// The Name field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b111f55e-9749-440e-83b2-fac1a7404b83</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Category_Constants.Name_FieldName)]
				public virtual string Name  {get; set;}
					
						/// <summary>
				/// The Wordpress Id field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 50b0e228-46cb-4527-be90-f170f6676deb</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Category_Constants.Wordpress_Id_FieldName)]
				public virtual string Wordpress_Id  {get; set;}
					
			
	}
}
namespace DEFExample.Models.Master.sitecore.templates.Data_Exchange.Providers.Wordpress.Folders
{


 	/// <summary>
	/// IWordpress_Value_Accessor_Sets_Root Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Folders/Wordpress Value Accessor Sets Root</para>	
	/// <para>ID: 48509877-4ef4-40db-8ab3-aaf542e86ea0</para>	
	/// </summary>
	[SitecoreType(TemplateId=IWordpress_Value_Accessor_Sets_Root_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IWordpress_Value_Accessor_Sets_Root : IGlassBase 
	{
				}

    [ExcludeFromCodeCoverage]
	public static partial class IWordpress_Value_Accessor_Sets_Root_Constants{

			public const string TemplateIdString = "48509877-4ef4-40db-8ab3-aaf542e86ea0";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Wordpress Value Accessor Sets Root";

			

	}

	
	/// <summary>
	/// Wordpress_Value_Accessor_Sets_Root
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Folders/Wordpress Value Accessor Sets Root</para>	
	/// <para>ID: 48509877-4ef4-40db-8ab3-aaf542e86ea0</para>	
	/// </summary>
    [ExcludeFromCodeCoverage]
	[SitecoreType(TemplateId=IWordpress_Value_Accessor_Sets_Root_Constants.TemplateIdString)] //, Cachable = true
	public partial class Wordpress_Value_Accessor_Sets_Root  : GlassBase, IWordpress_Value_Accessor_Sets_Root 
	{
	   
			
	}
}
namespace DEFExample.Models.Master.sitecore.templates.Example.Interfaces
{


 	/// <summary>
	/// I_Tag Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Example/Interfaces/_Tag</para>	
	/// <para>ID: 49c8e839-9a9a-4d0a-aa0b-1998951d5501</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Tag_Constants.TemplateIdString )] //, Cachable = true
	public partial interface I_Tag : IGlassBase 
	{
								/// <summary>
					/// The Name field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: b2e51da9-ce69-4371-81fd-bcde13b5f944</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Tag_Constants.Name_FieldName)]
					string Name  {get; set;}
			
								/// <summary>
					/// The Wordpress Id field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: a7351bd6-67e6-4118-bdf9-602f42abb4cf</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Tag_Constants.Wordpress_Id_FieldName)]
					string Wordpress_Id  {get; set;}
			
				}

    [ExcludeFromCodeCoverage]
	public static partial class I_Tag_Constants{

			public const string TemplateIdString = "49c8e839-9a9a-4d0a-aa0b-1998951d5501";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Tag";

					
			public static readonly ID Name_FieldId = new ID("b2e51da9-ce69-4371-81fd-bcde13b5f944");
			public const string Name_FieldName = "Name";
			
					
			public static readonly ID Wordpress_Id_FieldId = new ID("a7351bd6-67e6-4118-bdf9-602f42abb4cf");
			public const string Wordpress_Id_FieldName = "Wordpress Id";
			
			

	}

	
	/// <summary>
	/// _Tag
	/// <para></para>
	/// <para>Path: /sitecore/templates/Example/Interfaces/_Tag</para>	
	/// <para>ID: 49c8e839-9a9a-4d0a-aa0b-1998951d5501</para>	
	/// </summary>
    [ExcludeFromCodeCoverage]
	[SitecoreType(TemplateId=I_Tag_Constants.TemplateIdString)] //, Cachable = true
	public partial class _Tag  : GlassBase, I_Tag 
	{
	   
						/// <summary>
				/// The Name field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b2e51da9-ce69-4371-81fd-bcde13b5f944</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Tag_Constants.Name_FieldName)]
				public virtual string Name  {get; set;}
					
						/// <summary>
				/// The Wordpress Id field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: a7351bd6-67e6-4118-bdf9-602f42abb4cf</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Tag_Constants.Wordpress_Id_FieldName)]
				public virtual string Wordpress_Id  {get; set;}
					
			
	}
}
namespace DEFExample.Models.Master.sitecore.templates.Example.Content_Type.Blogs
{


 	/// <summary>
	/// ICategory Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Example/Content Type/Blogs/Category</para>	
	/// <para>ID: 4d1774a8-f057-4087-8c05-d258e72f567d</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICategory_Constants.TemplateIdString )] //, Cachable = true
	public partial interface ICategory : IGlassBase , global::DEFExample.Models.Master.sitecore.templates.Example.Interfaces.I_Category
	{
				}

    [ExcludeFromCodeCoverage]
	public static partial class ICategory_Constants{

			public const string TemplateIdString = "4d1774a8-f057-4087-8c05-d258e72f567d";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Category";

					
			public static readonly ID Name_FieldId = new ID("b111f55e-9749-440e-83b2-fac1a7404b83");
			public const string Name_FieldName = "Name";
			
					
			public static readonly ID Wordpress_Id_FieldId = new ID("50b0e228-46cb-4527-be90-f170f6676deb");
			public const string Wordpress_Id_FieldName = "Wordpress Id";
			
			

	}

	
	/// <summary>
	/// Category
	/// <para></para>
	/// <para>Path: /sitecore/templates/Example/Content Type/Blogs/Category</para>	
	/// <para>ID: 4d1774a8-f057-4087-8c05-d258e72f567d</para>	
	/// </summary>
    [ExcludeFromCodeCoverage]
	[SitecoreType(TemplateId=ICategory_Constants.TemplateIdString)] //, Cachable = true
	public partial class Category  : GlassBase, ICategory 
	{
	   
						/// <summary>
				/// The Name field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b111f55e-9749-440e-83b2-fac1a7404b83</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICategory_Constants.Name_FieldName)]
				public virtual string Name  {get; set;}
					
						/// <summary>
				/// The Wordpress Id field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 50b0e228-46cb-4527-be90-f170f6676deb</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICategory_Constants.Wordpress_Id_FieldName)]
				public virtual string Wordpress_Id  {get; set;}
					
			
	}
}
namespace DEFExample.Models.Master.sitecore.templates.Data_Exchange.Providers.Wordpress.Folders
{


 	/// <summary>
	/// IWordpress_Value_Writers_Root Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Folders/Wordpress Value Writers Root</para>	
	/// <para>ID: 55211d4a-1e66-4e64-9c83-b1fd52560023</para>	
	/// </summary>
	[SitecoreType(TemplateId=IWordpress_Value_Writers_Root_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IWordpress_Value_Writers_Root : IGlassBase 
	{
				}

    [ExcludeFromCodeCoverage]
	public static partial class IWordpress_Value_Writers_Root_Constants{

			public const string TemplateIdString = "55211d4a-1e66-4e64-9c83-b1fd52560023";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Wordpress Value Writers Root";

			

	}

	
	/// <summary>
	/// Wordpress_Value_Writers_Root
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Folders/Wordpress Value Writers Root</para>	
	/// <para>ID: 55211d4a-1e66-4e64-9c83-b1fd52560023</para>	
	/// </summary>
    [ExcludeFromCodeCoverage]
	[SitecoreType(TemplateId=IWordpress_Value_Writers_Root_Constants.TemplateIdString)] //, Cachable = true
	public partial class Wordpress_Value_Writers_Root  : GlassBase, IWordpress_Value_Writers_Root 
	{
	   
			
	}
}
namespace DEFExample.Models.Master.sitecore.templates.Example.Interfaces
{


 	/// <summary>
	/// I_Blog Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Example/Interfaces/_Blog</para>	
	/// <para>ID: 5e8dadb7-40f9-403c-bb51-ff987627795d</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Blog_Constants.TemplateIdString )] //, Cachable = true
	public partial interface I_Blog : IGlassBase 
	{
								/// <summary>
					/// The Author field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: a088ed8c-0861-426f-a46d-bd250b3997bf</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Blog_Constants.Author_FieldName)]
					string Author  {get; set;}
			
								/// <summary>
					/// The Categories field.
					/// <para></para>
					/// <para>Field Type: Treelist</para>		
					/// <para>Field ID: 71a8d0db-345a-41bc-ab09-d7b5ce4dc50a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Blog_Constants.Categories_FieldName)]
					IEnumerable<Guid> Categories  {get; set;}
			
								/// <summary>
					/// The Comment Status field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: f7e8892f-1de3-42ab-9077-6d22f8637938</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Blog_Constants.Comment_Status_FieldName)]
					string Comment_Status  {get; set;}
			
								/// <summary>
					/// The Content field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 01dfd93b-ee28-4021-9486-10ceed6e2329</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Blog_Constants.Content_FieldName)]
					string Content  {get; set;}
			
								/// <summary>
					/// The Date Gmt field.
					/// <para></para>
					/// <para>Field Type: Date</para>		
					/// <para>Field ID: 63e76bee-5109-48e9-a6e0-9bcfb0e39d15</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Blog_Constants.Date_Gmt_FieldName)]
					DateTime Date_Gmt  {get; set;}
			
								/// <summary>
					/// The Date field.
					/// <para></para>
					/// <para>Field Type: Date</para>		
					/// <para>Field ID: 88746c69-6b1b-4670-a2ab-3e410dc9f46d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Blog_Constants.Date_FieldName)]
					DateTime Date  {get; set;}
			
								/// <summary>
					/// The Excerpt field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 30a0549c-aad0-48de-98ce-4ca6679a5161</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Blog_Constants.Excerpt_FieldName)]
					string Excerpt  {get; set;}
			
								/// <summary>
					/// The Image Link field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: ab051020-8659-48e8-bfe1-b838b5d13160</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Blog_Constants.Image_Link_FieldName)]
					string Image_Link  {get; set;}
			
								/// <summary>
					/// The Link field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: ccf5a196-60e4-4108-b9e6-df87e8d34d6c</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Blog_Constants.Link_FieldName)]
					string Link  {get; set;}
			
								/// <summary>
					/// The Modified Date Gmt field.
					/// <para></para>
					/// <para>Field Type: Date</para>		
					/// <para>Field ID: 04e7e313-2681-4ec3-a5f8-9d9f4cf623ac</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Blog_Constants.Modified_Date_Gmt_FieldName)]
					DateTime Modified_Date_Gmt  {get; set;}
			
								/// <summary>
					/// The Modified Date field.
					/// <para></para>
					/// <para>Field Type: Date</para>		
					/// <para>Field ID: e5962ad0-9ab7-4abe-a699-18c0a2a29454</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Blog_Constants.Modified_Date_FieldName)]
					DateTime Modified_Date  {get; set;}
			
								/// <summary>
					/// The Ping Status field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 40563313-903a-471e-8cd5-1abb5897b38f</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Blog_Constants.Ping_Status_FieldName)]
					string Ping_Status  {get; set;}
			
								/// <summary>
					/// The Slug field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: f80740ff-ff83-4a59-9885-c2c4c0b30c91</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Blog_Constants.Slug_FieldName)]
					string Slug  {get; set;}
			
								/// <summary>
					/// The Status field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 7f70c3a2-424d-4427-b500-17a79bcace31</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Blog_Constants.Status_FieldName)]
					string Status  {get; set;}
			
								/// <summary>
					/// The Sticky field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 1672750f-3b0d-448d-8ab4-68b101dab9d4</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Blog_Constants.Sticky_FieldName)]
					string Sticky  {get; set;}
			
								/// <summary>
					/// The Tags field.
					/// <para></para>
					/// <para>Field Type: Treelist</para>		
					/// <para>Field ID: 0b512b3b-d866-466f-8f78-e017bbed3040</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Blog_Constants.Tags_FieldName)]
					IEnumerable<Guid> Tags  {get; set;}
			
								/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 27481025-7bf4-4fd5-9f84-d24c54ecae19</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Blog_Constants.Title_FieldName)]
					string Title  {get; set;}
			
								/// <summary>
					/// The Type field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 94a67fdb-8647-44a9-9cf3-bc44c7b5b480</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Blog_Constants.Type_FieldName)]
					string Type  {get; set;}
			
								/// <summary>
					/// The Wordpress Id field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 3a289128-d373-4a81-905e-f31abf44de69</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Blog_Constants.Wordpress_Id_FieldName)]
					string Wordpress_Id  {get; set;}
			
				}

    [ExcludeFromCodeCoverage]
	public static partial class I_Blog_Constants{

			public const string TemplateIdString = "5e8dadb7-40f9-403c-bb51-ff987627795d";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Blog";

					
			public static readonly ID Author_FieldId = new ID("a088ed8c-0861-426f-a46d-bd250b3997bf");
			public const string Author_FieldName = "Author";
			
					
			public static readonly ID Categories_FieldId = new ID("71a8d0db-345a-41bc-ab09-d7b5ce4dc50a");
			public const string Categories_FieldName = "Categories";
			
					
			public static readonly ID Comment_Status_FieldId = new ID("f7e8892f-1de3-42ab-9077-6d22f8637938");
			public const string Comment_Status_FieldName = "Comment Status";
			
					
			public static readonly ID Content_FieldId = new ID("01dfd93b-ee28-4021-9486-10ceed6e2329");
			public const string Content_FieldName = "Content";
			
					
			public static readonly ID Date_Gmt_FieldId = new ID("63e76bee-5109-48e9-a6e0-9bcfb0e39d15");
			public const string Date_Gmt_FieldName = "Date Gmt";
			
					
			public static readonly ID Date_FieldId = new ID("88746c69-6b1b-4670-a2ab-3e410dc9f46d");
			public const string Date_FieldName = "Date";
			
					
			public static readonly ID Excerpt_FieldId = new ID("30a0549c-aad0-48de-98ce-4ca6679a5161");
			public const string Excerpt_FieldName = "Excerpt";
			
					
			public static readonly ID Image_Link_FieldId = new ID("ab051020-8659-48e8-bfe1-b838b5d13160");
			public const string Image_Link_FieldName = "Image Link";
			
					
			public static readonly ID Link_FieldId = new ID("ccf5a196-60e4-4108-b9e6-df87e8d34d6c");
			public const string Link_FieldName = "Link";
			
					
			public static readonly ID Modified_Date_Gmt_FieldId = new ID("04e7e313-2681-4ec3-a5f8-9d9f4cf623ac");
			public const string Modified_Date_Gmt_FieldName = "Modified Date Gmt";
			
					
			public static readonly ID Modified_Date_FieldId = new ID("e5962ad0-9ab7-4abe-a699-18c0a2a29454");
			public const string Modified_Date_FieldName = "Modified Date";
			
					
			public static readonly ID Ping_Status_FieldId = new ID("40563313-903a-471e-8cd5-1abb5897b38f");
			public const string Ping_Status_FieldName = "Ping Status";
			
					
			public static readonly ID Slug_FieldId = new ID("f80740ff-ff83-4a59-9885-c2c4c0b30c91");
			public const string Slug_FieldName = "Slug";
			
					
			public static readonly ID Status_FieldId = new ID("7f70c3a2-424d-4427-b500-17a79bcace31");
			public const string Status_FieldName = "Status";
			
					
			public static readonly ID Sticky_FieldId = new ID("1672750f-3b0d-448d-8ab4-68b101dab9d4");
			public const string Sticky_FieldName = "Sticky";
			
					
			public static readonly ID Tags_FieldId = new ID("0b512b3b-d866-466f-8f78-e017bbed3040");
			public const string Tags_FieldName = "Tags";
			
					
			public static readonly ID Title_FieldId = new ID("27481025-7bf4-4fd5-9f84-d24c54ecae19");
			public const string Title_FieldName = "Title";
			
					
			public static readonly ID Type_FieldId = new ID("94a67fdb-8647-44a9-9cf3-bc44c7b5b480");
			public const string Type_FieldName = "Type";
			
					
			public static readonly ID Wordpress_Id_FieldId = new ID("3a289128-d373-4a81-905e-f31abf44de69");
			public const string Wordpress_Id_FieldName = "Wordpress Id";
			
			

	}

	
	/// <summary>
	/// _Blog
	/// <para></para>
	/// <para>Path: /sitecore/templates/Example/Interfaces/_Blog</para>	
	/// <para>ID: 5e8dadb7-40f9-403c-bb51-ff987627795d</para>	
	/// </summary>
    [ExcludeFromCodeCoverage]
	[SitecoreType(TemplateId=I_Blog_Constants.TemplateIdString)] //, Cachable = true
	public partial class _Blog  : GlassBase, I_Blog 
	{
	   
						/// <summary>
				/// The Author field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: a088ed8c-0861-426f-a46d-bd250b3997bf</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Blog_Constants.Author_FieldName)]
				public virtual string Author  {get; set;}
					
						/// <summary>
				/// The Categories field.
				/// <para></para>
				/// <para>Field Type: Treelist</para>		
				/// <para>Field ID: 71a8d0db-345a-41bc-ab09-d7b5ce4dc50a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Blog_Constants.Categories_FieldName)]
				public virtual IEnumerable<Guid> Categories  {get; set;}
					
						/// <summary>
				/// The Comment Status field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f7e8892f-1de3-42ab-9077-6d22f8637938</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Blog_Constants.Comment_Status_FieldName)]
				public virtual string Comment_Status  {get; set;}
					
						/// <summary>
				/// The Content field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 01dfd93b-ee28-4021-9486-10ceed6e2329</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Blog_Constants.Content_FieldName)]
				public virtual string Content  {get; set;}
					
						/// <summary>
				/// The Date Gmt field.
				/// <para></para>
				/// <para>Field Type: Date</para>		
				/// <para>Field ID: 63e76bee-5109-48e9-a6e0-9bcfb0e39d15</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Blog_Constants.Date_Gmt_FieldName)]
				public virtual DateTime Date_Gmt  {get; set;}
					
						/// <summary>
				/// The Date field.
				/// <para></para>
				/// <para>Field Type: Date</para>		
				/// <para>Field ID: 88746c69-6b1b-4670-a2ab-3e410dc9f46d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Blog_Constants.Date_FieldName)]
				public virtual DateTime Date  {get; set;}
					
						/// <summary>
				/// The Excerpt field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 30a0549c-aad0-48de-98ce-4ca6679a5161</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Blog_Constants.Excerpt_FieldName)]
				public virtual string Excerpt  {get; set;}
					
						/// <summary>
				/// The Image Link field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ab051020-8659-48e8-bfe1-b838b5d13160</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Blog_Constants.Image_Link_FieldName)]
				public virtual string Image_Link  {get; set;}
					
						/// <summary>
				/// The Link field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ccf5a196-60e4-4108-b9e6-df87e8d34d6c</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Blog_Constants.Link_FieldName)]
				public virtual string Link  {get; set;}
					
						/// <summary>
				/// The Modified Date Gmt field.
				/// <para></para>
				/// <para>Field Type: Date</para>		
				/// <para>Field ID: 04e7e313-2681-4ec3-a5f8-9d9f4cf623ac</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Blog_Constants.Modified_Date_Gmt_FieldName)]
				public virtual DateTime Modified_Date_Gmt  {get; set;}
					
						/// <summary>
				/// The Modified Date field.
				/// <para></para>
				/// <para>Field Type: Date</para>		
				/// <para>Field ID: e5962ad0-9ab7-4abe-a699-18c0a2a29454</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Blog_Constants.Modified_Date_FieldName)]
				public virtual DateTime Modified_Date  {get; set;}
					
						/// <summary>
				/// The Ping Status field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 40563313-903a-471e-8cd5-1abb5897b38f</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Blog_Constants.Ping_Status_FieldName)]
				public virtual string Ping_Status  {get; set;}
					
						/// <summary>
				/// The Slug field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f80740ff-ff83-4a59-9885-c2c4c0b30c91</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Blog_Constants.Slug_FieldName)]
				public virtual string Slug  {get; set;}
					
						/// <summary>
				/// The Status field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 7f70c3a2-424d-4427-b500-17a79bcace31</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Blog_Constants.Status_FieldName)]
				public virtual string Status  {get; set;}
					
						/// <summary>
				/// The Sticky field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 1672750f-3b0d-448d-8ab4-68b101dab9d4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Blog_Constants.Sticky_FieldName)]
				public virtual string Sticky  {get; set;}
					
						/// <summary>
				/// The Tags field.
				/// <para></para>
				/// <para>Field Type: Treelist</para>		
				/// <para>Field ID: 0b512b3b-d866-466f-8f78-e017bbed3040</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Blog_Constants.Tags_FieldName)]
				public virtual IEnumerable<Guid> Tags  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 27481025-7bf4-4fd5-9f84-d24c54ecae19</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Blog_Constants.Title_FieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The Type field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 94a67fdb-8647-44a9-9cf3-bc44c7b5b480</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Blog_Constants.Type_FieldName)]
				public virtual string Type  {get; set;}
					
						/// <summary>
				/// The Wordpress Id field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 3a289128-d373-4a81-905e-f31abf44de69</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Blog_Constants.Wordpress_Id_FieldName)]
				public virtual string Wordpress_Id  {get; set;}
					
			
	}
}
namespace DEFExample.Models.Master.sitecore.templates.Data_Exchange.Providers.Wordpress.Folders
{


 	/// <summary>
	/// IWordpress_Apply_Mapping_Rules_Root Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Folders/Wordpress Apply Mapping Rules Root</para>	
	/// <para>ID: 7075528d-41bf-4284-8fb5-6a0718837388</para>	
	/// </summary>
	[SitecoreType(TemplateId=IWordpress_Apply_Mapping_Rules_Root_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IWordpress_Apply_Mapping_Rules_Root : IGlassBase 
	{
				}

    [ExcludeFromCodeCoverage]
	public static partial class IWordpress_Apply_Mapping_Rules_Root_Constants{

			public const string TemplateIdString = "7075528d-41bf-4284-8fb5-6a0718837388";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Wordpress Apply Mapping Rules Root";

			

	}

	
	/// <summary>
	/// Wordpress_Apply_Mapping_Rules_Root
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Folders/Wordpress Apply Mapping Rules Root</para>	
	/// <para>ID: 7075528d-41bf-4284-8fb5-6a0718837388</para>	
	/// </summary>
    [ExcludeFromCodeCoverage]
	[SitecoreType(TemplateId=IWordpress_Apply_Mapping_Rules_Root_Constants.TemplateIdString)] //, Cachable = true
	public partial class Wordpress_Apply_Mapping_Rules_Root  : GlassBase, IWordpress_Apply_Mapping_Rules_Root 
	{
	   
			
	}
}
namespace DEFExample.Models.Master.sitecore.templates.Data_Exchange.Providers.Wordpress.Folders
{


 	/// <summary>
	/// IWordpress_Filter_Expressions_Root Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Folders/Wordpress Filter Expressions Root</para>	
	/// <para>ID: 7125c164-b8f8-45e3-af38-3d3de38ff820</para>	
	/// </summary>
	[SitecoreType(TemplateId=IWordpress_Filter_Expressions_Root_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IWordpress_Filter_Expressions_Root : IGlassBase 
	{
				}

    [ExcludeFromCodeCoverage]
	public static partial class IWordpress_Filter_Expressions_Root_Constants{

			public const string TemplateIdString = "7125c164-b8f8-45e3-af38-3d3de38ff820";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Wordpress Filter Expressions Root";

			

	}

	
	/// <summary>
	/// Wordpress_Filter_Expressions_Root
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Folders/Wordpress Filter Expressions Root</para>	
	/// <para>ID: 7125c164-b8f8-45e3-af38-3d3de38ff820</para>	
	/// </summary>
    [ExcludeFromCodeCoverage]
	[SitecoreType(TemplateId=IWordpress_Filter_Expressions_Root_Constants.TemplateIdString)] //, Cachable = true
	public partial class Wordpress_Filter_Expressions_Root  : GlassBase, IWordpress_Filter_Expressions_Root 
	{
	   
			
	}
}
namespace DEFExample.Models.Master.sitecore.templates.Data_Exchange.Providers.Wordpress.Folders
{


 	/// <summary>
	/// IWordpress_Mappings_Applied_Action_Rules_Root Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Folders/Wordpress Mappings Applied Action Rules Root</para>	
	/// <para>ID: a6e4bfec-6c87-438c-a719-ef7ffbd29653</para>	
	/// </summary>
	[SitecoreType(TemplateId=IWordpress_Mappings_Applied_Action_Rules_Root_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IWordpress_Mappings_Applied_Action_Rules_Root : IGlassBase 
	{
				}

    [ExcludeFromCodeCoverage]
	public static partial class IWordpress_Mappings_Applied_Action_Rules_Root_Constants{

			public const string TemplateIdString = "a6e4bfec-6c87-438c-a719-ef7ffbd29653";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Wordpress Mappings Applied Action Rules Root";

			

	}

	
	/// <summary>
	/// Wordpress_Mappings_Applied_Action_Rules_Root
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Folders/Wordpress Mappings Applied Action Rules Root</para>	
	/// <para>ID: a6e4bfec-6c87-438c-a719-ef7ffbd29653</para>	
	/// </summary>
    [ExcludeFromCodeCoverage]
	[SitecoreType(TemplateId=IWordpress_Mappings_Applied_Action_Rules_Root_Constants.TemplateIdString)] //, Cachable = true
	public partial class Wordpress_Mappings_Applied_Action_Rules_Root  : GlassBase, IWordpress_Mappings_Applied_Action_Rules_Root 
	{
	   
			
	}
}
namespace DEFExample.Models.Master.sitecore.templates.Data_Exchange.Providers.Wordpress.Pipeline_Steps
{


 	/// <summary>
	/// IWordpress_Pipeline_Step Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Pipeline Steps/Wordpress Pipeline Step</para>	
	/// <para>ID: bac188f2-3339-4f46-9dbe-72cde090b6a2</para>	
	/// </summary>
	[SitecoreType(TemplateId=IWordpress_Pipeline_Step_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IWordpress_Pipeline_Step : IGlassBase 
	{
								/// <summary>
					/// The EndpointFrom field.
					/// <para></para>
					/// <para>Field Type: Droptree</para>		
					/// <para>Field ID: 123bbea0-4abc-48b2-a879-5913a75fb8c6</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IWordpress_Pipeline_Step_Constants.EndpointFrom_FieldName)]
					Guid EndpointFrom  {get; set;}
			
				}

    [ExcludeFromCodeCoverage]
	public static partial class IWordpress_Pipeline_Step_Constants{

			public const string TemplateIdString = "bac188f2-3339-4f46-9dbe-72cde090b6a2";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Wordpress Pipeline Step";

					
			public static readonly ID EndpointFrom_FieldId = new ID("123bbea0-4abc-48b2-a879-5913a75fb8c6");
			public const string EndpointFrom_FieldName = "EndpointFrom";
			
			

	}

	
	/// <summary>
	/// Wordpress_Pipeline_Step
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Pipeline Steps/Wordpress Pipeline Step</para>	
	/// <para>ID: bac188f2-3339-4f46-9dbe-72cde090b6a2</para>	
	/// </summary>
    [ExcludeFromCodeCoverage]
	[SitecoreType(TemplateId=IWordpress_Pipeline_Step_Constants.TemplateIdString)] //, Cachable = true
	public partial class Wordpress_Pipeline_Step  : GlassBase, IWordpress_Pipeline_Step 
	{
	   
						/// <summary>
				/// The EndpointFrom field.
				/// <para></para>
				/// <para>Field Type: Droptree</para>		
				/// <para>Field ID: 123bbea0-4abc-48b2-a879-5913a75fb8c6</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IWordpress_Pipeline_Step_Constants.EndpointFrom_FieldName)]
				public virtual Guid EndpointFrom  {get; set;}
					
			
	}
}
namespace DEFExample.Models.Master.sitecore.templates.Data_Exchange.Providers.Wordpress.Folders
{


 	/// <summary>
	/// IWordpress_Endpoints_Root Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Folders/Wordpress Endpoints Root</para>	
	/// <para>ID: bfc9df67-54a5-4327-a059-0b4f249a8479</para>	
	/// </summary>
	[SitecoreType(TemplateId=IWordpress_Endpoints_Root_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IWordpress_Endpoints_Root : IGlassBase 
	{
				}

    [ExcludeFromCodeCoverage]
	public static partial class IWordpress_Endpoints_Root_Constants{

			public const string TemplateIdString = "bfc9df67-54a5-4327-a059-0b4f249a8479";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Wordpress Endpoints Root";

			

	}

	
	/// <summary>
	/// Wordpress_Endpoints_Root
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Folders/Wordpress Endpoints Root</para>	
	/// <para>ID: bfc9df67-54a5-4327-a059-0b4f249a8479</para>	
	/// </summary>
    [ExcludeFromCodeCoverage]
	[SitecoreType(TemplateId=IWordpress_Endpoints_Root_Constants.TemplateIdString)] //, Cachable = true
	public partial class Wordpress_Endpoints_Root  : GlassBase, IWordpress_Endpoints_Root 
	{
	   
			
	}
}
namespace DEFExample.Models.Master.sitecore.templates.Example.Content_Type.Blogs
{


 	/// <summary>
	/// ITag Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Example/Content Type/Blogs/Tag</para>	
	/// <para>ID: c21eb487-d2d1-4752-b1f4-76a8e111e00b</para>	
	/// </summary>
	[SitecoreType(TemplateId=ITag_Constants.TemplateIdString )] //, Cachable = true
	public partial interface ITag : IGlassBase , global::DEFExample.Models.Master.sitecore.templates.Example.Interfaces.I_Tag
	{
				}

    [ExcludeFromCodeCoverage]
	public static partial class ITag_Constants{

			public const string TemplateIdString = "c21eb487-d2d1-4752-b1f4-76a8e111e00b";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Tag";

					
			public static readonly ID Name_FieldId = new ID("b2e51da9-ce69-4371-81fd-bcde13b5f944");
			public const string Name_FieldName = "Name";
			
					
			public static readonly ID Wordpress_Id_FieldId = new ID("a7351bd6-67e6-4118-bdf9-602f42abb4cf");
			public const string Wordpress_Id_FieldName = "Wordpress Id";
			
			

	}

	
	/// <summary>
	/// Tag
	/// <para></para>
	/// <para>Path: /sitecore/templates/Example/Content Type/Blogs/Tag</para>	
	/// <para>ID: c21eb487-d2d1-4752-b1f4-76a8e111e00b</para>	
	/// </summary>
    [ExcludeFromCodeCoverage]
	[SitecoreType(TemplateId=ITag_Constants.TemplateIdString)] //, Cachable = true
	public partial class Tag  : GlassBase, ITag 
	{
	   
						/// <summary>
				/// The Name field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b2e51da9-ce69-4371-81fd-bcde13b5f944</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ITag_Constants.Name_FieldName)]
				public virtual string Name  {get; set;}
					
						/// <summary>
				/// The Wordpress Id field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: a7351bd6-67e6-4118-bdf9-602f42abb4cf</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ITag_Constants.Wordpress_Id_FieldName)]
				public virtual string Wordpress_Id  {get; set;}
					
			
	}
}
namespace DEFExample.Models.Master.sitecore.templates.Data_Exchange.Providers.Wordpress.Folders
{


 	/// <summary>
	/// IWordpress_Tenant_Settings_Root Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Folders/Wordpress Tenant Settings Root</para>	
	/// <para>ID: d64026ef-db58-4bae-b576-6537fa755058</para>	
	/// </summary>
	[SitecoreType(TemplateId=IWordpress_Tenant_Settings_Root_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IWordpress_Tenant_Settings_Root : IGlassBase 
	{
				}

    [ExcludeFromCodeCoverage]
	public static partial class IWordpress_Tenant_Settings_Root_Constants{

			public const string TemplateIdString = "d64026ef-db58-4bae-b576-6537fa755058";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Wordpress Tenant Settings Root";

			

	}

	
	/// <summary>
	/// Wordpress_Tenant_Settings_Root
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Folders/Wordpress Tenant Settings Root</para>	
	/// <para>ID: d64026ef-db58-4bae-b576-6537fa755058</para>	
	/// </summary>
    [ExcludeFromCodeCoverage]
	[SitecoreType(TemplateId=IWordpress_Tenant_Settings_Root_Constants.TemplateIdString)] //, Cachable = true
	public partial class Wordpress_Tenant_Settings_Root  : GlassBase, IWordpress_Tenant_Settings_Root 
	{
	   
			
	}
}
namespace DEFExample.Models.Master.sitecore.templates.Data_Exchange.Providers.Wordpress.Folders
{


 	/// <summary>
	/// IWordpress_Value_Accessors_Root Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Folders/Wordpress Value Accessors Root</para>	
	/// <para>ID: de9f1cfb-9779-418e-b02c-24c5e327f027</para>	
	/// </summary>
	[SitecoreType(TemplateId=IWordpress_Value_Accessors_Root_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IWordpress_Value_Accessors_Root : IGlassBase 
	{
				}

    [ExcludeFromCodeCoverage]
	public static partial class IWordpress_Value_Accessors_Root_Constants{

			public const string TemplateIdString = "de9f1cfb-9779-418e-b02c-24c5e327f027";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Wordpress Value Accessors Root";

			

	}

	
	/// <summary>
	/// Wordpress_Value_Accessors_Root
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Folders/Wordpress Value Accessors Root</para>	
	/// <para>ID: de9f1cfb-9779-418e-b02c-24c5e327f027</para>	
	/// </summary>
    [ExcludeFromCodeCoverage]
	[SitecoreType(TemplateId=IWordpress_Value_Accessors_Root_Constants.TemplateIdString)] //, Cachable = true
	public partial class Wordpress_Value_Accessors_Root  : GlassBase, IWordpress_Value_Accessors_Root 
	{
	   
			
	}
}
namespace DEFExample.Models.Master.sitecore.templates.Data_Exchange.Providers.Wordpress.Folders
{


 	/// <summary>
	/// IWordpress_Value_Readers_Root Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Folders/Wordpress Value Readers Root</para>	
	/// <para>ID: f4ab8356-ab87-4059-ae2f-94b84fb23944</para>	
	/// </summary>
	[SitecoreType(TemplateId=IWordpress_Value_Readers_Root_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IWordpress_Value_Readers_Root : IGlassBase 
	{
				}

    [ExcludeFromCodeCoverage]
	public static partial class IWordpress_Value_Readers_Root_Constants{

			public const string TemplateIdString = "f4ab8356-ab87-4059-ae2f-94b84fb23944";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Wordpress Value Readers Root";

			

	}

	
	/// <summary>
	/// Wordpress_Value_Readers_Root
	/// <para></para>
	/// <para>Path: /sitecore/templates/Data Exchange/Providers/Wordpress/Folders/Wordpress Value Readers Root</para>	
	/// <para>ID: f4ab8356-ab87-4059-ae2f-94b84fb23944</para>	
	/// </summary>
    [ExcludeFromCodeCoverage]
	[SitecoreType(TemplateId=IWordpress_Value_Readers_Root_Constants.TemplateIdString)] //, Cachable = true
	public partial class Wordpress_Value_Readers_Root  : GlassBase, IWordpress_Value_Readers_Root 
	{
	   
			
	}
}
